# ALS Project

## Family ALS History

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
%load_ext autoreload
%autoreload 2

## functions

##

In [79]:
family = pd.read_csv("data/FamilyHistory.csv")

In [80]:
print(family.shape)
family.head()

(1071, 39)

,subject_id,Family_History_Delta,Other_Specify,Family_Hx_of_ALS_Mutation,Family_Hx_of_ALS_Mutation_Other,Family_Hx_of_Neuro_Disease,Aunt,Aunt__Maternal_,Aunt__Paternal_,Cousin,...,Uncle,Uncle__Maternal_,Uncle__Paternal_,Family_Hx_of_Neuro_Disease_Other,Neurological_Disease,Neurological_Disease_Other,Son,Daughter,Sister,Brother
0,348,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1064,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3809,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,DAT,NaN,NaN,NaN,NaN,NaN
3,4877,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5918,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
cols = list(family.columns)
cols.remove('subject_id')

In [82]:
for col in cols:
    print("{}: {}".format(col, family[col].unique()))

Family_History_Delta: [ 0. nan]
Other_Specify: [nan]
Family_Hx_of_ALS_Mutation: [nan]
Family_Hx_of_ALS_Mutation_Other: [nan]
Family_Hx_of_Neuro_Disease: [nan 'ALS']
Aunt: [nan  1.]
Aunt__Maternal_: [nan  1.]
Aunt__Paternal_: [nan  1.]
Cousin: [nan  1.]
Cousin__Paternal_: [nan]
Cousin__Maternal_: [nan]
Father: [nan  1.]
Grandfather: [nan  1.]
Grandfather__Maternal_: [nan  1.]
Grandfather__Paternal_: [nan  1.]
Grandmother: [nan  1.]
Grandmother__Maternal_: [nan  1.]
Grandmother__Paternal_: [nan  1.]
Mother: [nan  1.]
Nephew: [nan  1.]
Nephew__Maternal_: [nan]
Nephew__Paternal_: [nan]
Niece: [nan  1.]
Niece__Maternal_: [nan]
Niece__Paternal_: [nan]
Other: [nan]
Sibling: [nan]
Volunteer: [nan]
Uncle: [nan  1.]
Uncle__Maternal_: [nan  1.]
Uncle__Paternal_: [nan  1.]
Family_Hx_of_Neuro_Disease_Other: [nan]
Neurological_Disease: [nan 'DAT' 'OTHER' 'STROKE-NOS' 'BRAIN TUMOR' "PARKINSON'S DISEASE"
 'DEMENTIA-NOS' 'ALS' 'STROKE-ISCHEMIC' 'STROKE-HEMORRHAGIC']
Neurological_Disease_Other: [nan 'RENAL CARCINOMA WITH CEREBRAL METASTARES' 'INCLUSION BODYMYOSITIS'
 "PARKINSON'S DISEASE (POST ENCEPHALITIC)" 'MYOPATHY' 'MULTIPLE SCLEROSIS'
 'MYOSITIS' 'SPINAL NERVE PARALYSIS'
 'POSSIBLE CHARLOT-MARIE TOOTH DISEASE' 'DYSTONIA'
 'CAROTID ENDO ARTECTOMY' 'EPILEPSY' 'ESSENTIAL TREMOR' '0' 'AUTISM'
 'POLIO' 'POLYOMYECITIS' 'PRIMARY SUPRANUCLEEAR PALSY' 'POLYNEUROPATHY'
 "BELL'S PALSY" 'TREMOR' 'BRIAN NEOPLASIA' 'CRAMPS'
 'HEMATOMA INTRACRANIAL' 'HEMOPLEGIA' 'MENTAL RETARDATION'
 'FIBROMYALGIA STROKE' 'FIBROMYALGIA' 'AIDS' 'SYNDROME GUILLAIN BARRE'
 'APEPLEX' 'PTOSIS' 'ED' 'SMA TYPE III' 'POLYMYOSITIS'
 'PATERNAL UNCLE SISTER' 'A NEURYNM RUPTURE' 'UPPER SPINAL CORD DEFECT'
 'DEATH BY CEREBRAL HAEMORRHAGE' 'SCHIZOPHRENIA' 'MYASTHENIA GRAVIS'
 'PALSY UNKNOWN AETIOLOGY' 'OPCA' "HUNTINGTON'S"
 'DEGENERATIVE JOINT DISEASE' 'BELLS PALSY TIC DOLOROUX'
 'MUSCULAR DYSTROPHY' 'SROKES' 'ALTRANSVERSE MYELITIS' 'DEPRESSION'
 'SPINAL CEREBELLAR ATAXIA' 'MULTIPLE SCLEROSIS SPINA BIFIDA' 'DYSKINESIA'
 'PSP' 'DOWNS SYNDROME CHILDHOOD EPILEPSY' 'LUPUS SYNOROME'
 "MENIERE'S DISEASE" 'NBIA'
 'PSYCHOMOLOR PROBLEMS WITH AMYOTROPHY DEATH: 9 YEARS OLD'
 'NEUROSURGICAL PROCEDURE FOR "CELLS DEAD"' 'GUILLAIN-BARRE SYNDROME'
 "MYOTONIC DYSTROPHIA 'CURSCHMANN-STEINERT'" 'SCHIZAPHRENIA IN MOTHER'
 'STROKE 1/2 SISTER' 'CEREBRAL PALSY' 'MENINGITIS'
 'VITAMIN B12 DEFICIENCY' 'SUICIDE' 'NOISE DEAFNESS' 'TORTICOLLIS'
 'NARCOLEPSY' 'OBS(ORGANIC BRAIN SYNDROME)']
Son: [nan  1.]
Daughter: [nan  1.]
Sister: [nan  1.]
Brother: [nan  1.]

In [83]:
columns_delete = [ 'Family_History_Delta', 'Other_Specify', 'Family_Hx_of_ALS_Mutation',
                 'Family_Hx_of_ALS_Mutation_Other', 'Cousin__Paternal_', 
                  'Cousin__Maternal_', 'Nephew__Maternal_', 
                  'Nephew__Paternal_', 'Niece__Maternal_', 'Niece__Paternal_', 
                  'Other', 'Sibling', 'Volunteer', 'Family_Hx_of_Neuro_Disease_Other']

In [84]:
for col in columns_delete:
    family.drop(col, axis=1, inplace=True)

In [85]:
family.head()

,subject_id,Family_Hx_of_Neuro_Disease,Aunt,Aunt__Maternal_,Aunt__Paternal_,Cousin,Father,Grandfather,Grandfather__Maternal_,Grandfather__Paternal_,...,Niece,Uncle,Uncle__Maternal_,Uncle__Paternal_,Neurological_Disease,Neurological_Disease_Other,Son,Daughter,Sister,Brother
0,348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3809,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,DAT,NaN,NaN,NaN,NaN,NaN
3,4877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
family.loc[family['Neurological_Disease'].isnull(), 'hist_neurological_disease'] = 1

In [87]:
family.head()

,subject_id,Family_Hx_of_Neuro_Disease,Aunt,Aunt__Maternal_,Aunt__Paternal_,Cousin,Father,Grandfather,Grandfather__Maternal_,Grandfather__Paternal_,...,Uncle,Uncle__Maternal_,Uncle__Paternal_,Neurological_Disease,Neurological_Disease_Other,Son,Daughter,Sister,Brother,hist_neurological_disease
0,348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,3809,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,DAT,NaN,NaN,NaN,NaN,NaN,NaN
3,4877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,5918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [88]:
family.fillna(0, inplace=True)
family.head()

,subject_id,Family_Hx_of_Neuro_Disease,Aunt,Aunt__Maternal_,Aunt__Paternal_,Cousin,Father,Grandfather,Grandfather__Maternal_,Grandfather__Paternal_,...,Uncle,Uncle__Maternal_,Uncle__Paternal_,Neurological_Disease,Neurological_Disease_Other,Son,Daughter,Sister,Brother,hist_neurological_disease
0,348,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,1.0
1,1064,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,1.0
2,3809,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,DAT,0,0.0,0.0,0.0,0.0,0.0
3,4877,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,1.0
4,5918,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,1.0

In [89]:
family.drop('Neurological_Disease', axis=1, inplace=True)

In [90]:
family.head()

,subject_id,Family_Hx_of_Neuro_Disease,Aunt,Aunt__Maternal_,Aunt__Paternal_,Cousin,Father,Grandfather,Grandfather__Maternal_,Grandfather__Paternal_,...,Niece,Uncle,Uncle__Maternal_,Uncle__Paternal_,Neurological_Disease_Other,Son,Daughter,Sister,Brother,hist_neurological_disease
0,348,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,1.0
1,1064,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,1.0
2,3809,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0
3,4877,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,1.0
4,5918,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,1.0

In [91]:
family.drop('Neurological_Disease_Other', axis=1, inplace=True)

In [92]:
family.head()

,subject_id,Family_Hx_of_Neuro_Disease,Aunt,Aunt__Maternal_,Aunt__Paternal_,Cousin,Father,Grandfather,Grandfather__Maternal_,Grandfather__Paternal_,...,Nephew,Niece,Uncle,Uncle__Maternal_,Uncle__Paternal_,Son,Daughter,Sister,Brother,hist_neurological_disease
0,348,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1064,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3809,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4877,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5918,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [93]:
# save the symptom encoded file for analysis
filename = 'clean_data/family.csv'
family.to_csv(filename, index=False)